### ISSUE TITLE
What does this node do  ?

### ISSUE THREAD

**Issue by dceejay** [hadrienk/node-red-contrib-nordic-thingy#1]
Hi

Any chance you could actually document what this node does in the README so that people can understand it ? Alternatively you could remove the "node-red" keyword from package.json, and we won't automatically index it on the flows.nodered.org site.

Thanks

**Comment by hadrienk** [comment]
Hi, 

I updated the description now. I will add more examples and details when the project I am developing this node for is over. 

Hadrien
