### ISSUE TITLE
No thingy found...?

### ISSUE THREAD

**Issue by kriedel** [hadrienk/node-red-contrib-nordic-thingy#2]
Hi,
I have installed as described but can't find any thingy by scanning. With node.js examples it is OK. 
 Node-RED version: v0.18.4
 Node.js  version: v6.11.5

Thanks,
Kai

**Comment by hadrienk** [comment]
I never finished the name filter functionality. I believe in order to
connect the thingies name must contain "hadrien" or "flokk" (case
insensitive).

https://github.com/hadrienk/node-red-contrib-nordic-thingy/blob/52da36f65a1f7952e37c5144b7b32ad056cedbeb/src/NodeThingy.ts#L20

**Comment by kriedel** [comment]
With "flokk" it works fine, I set the name with the android app.

Thanks.
